### PR TITLE
Bkg img fix

### PR DESCRIPTION
**Pull request by yadev64**
Bug Fixes ONLY. NO NEW FEATURE ACCEPTED!

Description

Related Issue

Motivation and Context

How Has This Been Tested?

Screenshots (if appropriate):

### CODE REVIEW

**Review by dauntlessnomad — COMMENTED** [review]
approved

**Review by shinenelson — COMMENTED** [review]
Mentioning my [review](https://github.com/MozillaKerala/Home/pull/34#pullrequestreview-128524416) about checking in `.DS_Store` files here too.

**Comment by syam3526** [comment]
@shinenelson   will make sure this never happens in the future

**Comment by syam3526** [comment]
@shinenelson can i remove the .DS files directly from master without doing pull. 
there are so many.

**Comment by shinenelson** [comment]
* `git checkout -b <new-branch-name> master`
* `find . -name '.DS_Store' -delete`
* `git add` <whichever files got deleted>
* `git commit -m 'remove unnecessary .DS_Store files (resolves https://github.com/MozillaKerala/Home/pull/34#pullrequestreview-128524416)`
* `git push origin <new-branch-name>`

**Comment by dauntlessnomad** [comment]
Thank you for that. Can i do it in the morning. I am on my phone .

**Comment by shinenelson** [comment]
Nobody is in a hurry here. :wink: (I took almost a month to come here to review these changes; even though I was not marked as a reviewer for these changes). This is not a critical bug in production that needs to be addressed immediately. Take your time. :+1:

**Comment by dauntlessnomad** [comment]
I have send you a mail regarding the portal.  Can you look into it.

**Comment by dauntlessnomad** [comment]
Will do the removal tommorow itselfs. 
Thank you for pointing out my mistakes.

**Pull request merged**
